export const Compliment = [
    'This is a sick song!',
    'This song is lit :o',
    'We also dig this track!',
    'New song, who dis?',
    'This is groovy!',
    'This genre is great!',
    'This song has a great beat!',
    'You like this song too?!?',
    'This song is HAWT!',
    'Sorry, I could not hear you over this sick song.',
    'This is one of our FAVE songs!',
    'We should see your songs more often!',
    'Do you hear that? It is another awesome song!',
    'Keep making more playlists with songs like these!',
    'What other amazing songs are you hiding from us?!',
    'This song should be illegal for how rad it is!',
    'Our team has to listen to this song!',
    'WHAT? You know this artist too!?',
    'Let us get boppin!',
    'See you on the dance floor!',
    'Turn it up!',
    'We need more music like this!',
    'This is not loud enough!',
    'We need some peanut butter with this jam!',
    'Where is the boombox when we need one?',
    'Let us get this party started!',
    'Boots and cats and boots and cats',
    'Looks like we are in TREBLE now!',
    'This song gives me the moves like Jagger!',
    'Turn the bass up!',
]